name: Tests and Lints packages

on:
  workflow_call:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Set up project
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test
